[package]
name = "srtmtiles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4"
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
dotenv = "0.15"
