[package]
name = "geodata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srtm = "0.1"
byteorder = "1.4"
